#-------------------------------
# Site Settings
title: Yuki Miura
description: Priam is a minimal portfolio theme for Jekyll.
color_scheme: auto # You have the option to choose between three modes: auto, light, and dark. The default mode is set to auto, which means that the color scheme will automatically adapt based on your operating system settings. This way, you can enjoy a personalized experience without having to manually switch between light and dark modes.


#-------------------------------
# Global Cover
global_cover:
  enable: true
  homepage_image: "/images/01.jpg" # This line allows you to add a beautiful image at the top of your site, creating an eye-catching visual element that enhances the overall appearance and appeal.


#-------------------------------
# Breadcrumbs
breadcrumbs:
  enable: true # This line of code enables you to easily incorporate breadcrumbs into your website. By setting the "enable" parameter to "true", breadcrumbs will be enabled on your website, allowing users to easily track their navigation and find relevant information. Conversely, setting the parameter to "false" will disable the display of breadcrumbs, removing this navigation feature from your website.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Research'
      url: '/projects/'
    - title: 'About'
      url: '/about/'
    - title: 'Publications'
      url: '/blog/'
    - title: 'Gallery'
      url: '/gallery/'


#-------------------------------
# Author Settings
author:
  author_name: Yuki Miura
  author_role: Research Scientist
  author_bio: 🧠 Neuroscience and Stem Cell Scientist ⭐️ Decoding the secrets of human brain development 💡 Passionate about unraveling neural circuit mysteries and tackling neuropsychiatric disorders 🧪 Expert in brain organoids, stem cell technologies, and functional cellular imaging to advance human neuroscience
  author_avatar: '/images/01-1.jpg'

#-------------------------------
# Research Settings
projects_settings:
  enable: true
  projects_title: Research
  projects_description:

#-------------------------------
# Gallery Section
gallery_settings:
  enable: true
  gallery_title: Gallery
  gallery_description:

#-------------------------------
# Social Icons Settings
social:
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/ykmiura"}
- {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-dribbble", name: "Dribbble" link: "https://dribbble.com"}
# Other icons can be found at https://fontawesome.com/search?o=r&m=free


#-------------------------------
# Contact Settings
contact:
  email: miurayuki0531@gmail.com # Add your form_id
  description: Priam comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Priam theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
